services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      AZURITE_ACCOUNTS: account1:key1:key2;account2:key1:key2
  
  cosmosdb-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    container_name: "cosmosdb-emulator"
    hostname: cosmosdb-emulator
    restart: always
    ports:
      - "8081:8081"
      - "1234:1234"

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: "servicebus-emulator"
    hostname: servicebus-emulator
    restart: always
    volumes:
      - ./localdev/ServiceBus_Emulator.Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "Secure!12346"
      ACCEPT_EULA: "Y"
    depends_on:
      - sqledge
    
  sqledge:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: "sqledge"
    hostname: sqledge
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Secure!12346"