include:
  - ./localdev/emulators.yaml

services:

  doner_types_builder:
    image: node:22
    platform: linux/amd64
    container_name: doner_types_builder
    restart: no
    working_dir: /app/shared/doner_types
    volumes:
      - ./functions:/app
      - /app/shared/doner_types/node_modules
      - node_modules_shared:/app/node_modules
      - doner_types_node_dist:/app/shared/doner_types/dist
      - node_modules_cache:/root/.npm
    command: >-
      sh -c "
      npm install --prefix /app &&
      npm install &&
      npm run build
      "

  place-search:
    image: node:22
    platform: linux/amd64
    container_name: "place-search"
    working_dir: /app/place-search
    volumes:
      - ./functions:/app
      - doner_types_node_dist:/app/shared/doner_types/dist
      - node_modules_shared:/app/node_modules
      - /app/place-search/node_modules
      - /app/place-search/dist
      - node_modules_cache:/root/.npm
    command: >-
      sh -c "
      npm install &&
      npm run dev
      "
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
      - azurite
      - doner_types_builder
    ports:
      - 7071:7071
    env_file:
      - ./functions/place-search/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

  image-classifier:
    image: node:22
    platform: linux/amd64
    container_name: "image-classifier"
    working_dir: /app/image-classifier
    volumes:
      - ./functions:/app
      - doner_types_node_dist:/app/shared/doner_types/dist
      - node_modules_shared:/app/node_modules
      - /app/image-classifier/node_modules
      - /app/image-classifier/dist
      - node_modules_cache:/root/.npm
    command: >-
      sh -c "
      npm install &&
      npm run dev
      "
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
      - azurite
      - doner_types_builder
    ports:
      - 7072:7072
    env_file:
      - ./functions/image-classifier/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

  llm-analyzer:
    image: node:22
    platform: linux/amd64
    container_name: "llm-analyzer"
    working_dir: /app/llm-analyzer
    volumes:
      - ./functions:/app
      - doner_types_node_dist:/app/shared/doner_types/dist
      - node_modules_shared:/app/node_modules
      - /app/llm-analyzer/node_modules
      - /app/llm-analyzer/dist
      - node_modules_cache:/root/.npm
    command: >-
      sh -c "
      npm install &&
      npm run dev
      "
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
      - doner_types_builder
    ports:
      - 7073:7073
    env_file:
      - ./functions/llm-analyzer/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

  shops:
    image: node:22
    platform: linux/amd64
    container_name: shops
    working_dir: /app/shops
    volumes:
      - ./functions:/app
      - doner_types_node_dist:/app/shared/doner_types/dist
      - node_modules_shared:/app/node_modules
      - /app/shops/node_modules
      - /app/shops/dist
      - node_modules_cache:/root/.npm
    command: >-
      sh -c "
      npm install &&
      npm run dev
      "
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
      - doner_types_builder
    ports:
      - 7074:7074
    env_file:
      - ./functions/shops/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"


  places-reader:
    image: node:22
    container_name: "places-reader"
    working_dir: /app
    restart: always
    volumes:
      - ./helper/service-bus-reader:/app
      - node_modules_service-bus-reader:/app/node_modules
      - node_dist_service-bus-reader:/app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - servicebus-emulator
    environment:
      SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://servicebus-emulator:5672;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      QUEUE_NAME: "places"
      BATCH_SIZE: "10"
    profiles:
      - reader
  
  image-classifier-reader:
    image: node:22
    container_name: "image-classifier-reader"
    working_dir: /app
    restart: always
    volumes:
      - ./helper/service-bus-reader:/app
      - node_modules_service-bus-reader:/app/node_modules
      - node_dist_service-bus-reader:/app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - servicebus-emulator
    environment:
      SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://servicebus-emulator:5672;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      QUEUE_NAME: "classified-images"
      BATCH_SIZE: "10"
    profiles:
      - reader

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    command: ["azurite", "-l", "/data", "--blobHost", "0.0.0.0","--queueHost", "0.0.0.0", "--tableHost", "0.0.0.0", "--skipApiVersionCheck"]
    ports:
      - 7074:7074
    env_file:
      - ./functions/shops/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

volumes:
  doner_types_node_dist:
  node_modules_cache:
  node_modules_shared:
