services:

  place-search:
    image: node:22
    container_name: "place-search"
    working_dir: /app/place-search
    volumes:
      - ./functions:/app
      - node_modules_place-search:/app/place-search/node_modules
      - node_modules_shared:/app/shared/doner_types/node_modules
      - node_dist_place-search:/app/place-search/dist
      - node_dist_shared:/app/shared/doner_types/dist
    command: >-
      sh -c "npm install --prefix ../shared/doner_types &&
      npm run build --prefix ../shared/doner_types &&
      npm install &&
      npm run dev"
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
      - azurite
    ports:
      - 7071:7071
    env_file:
      - ./functions/place-search/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

  image-classifier:
    image: node:22
    container_name: "image-classifier"
    working_dir: /app/image-classifier
    volumes:
      - ./functions:/app
      - node_modules_image-classifier:/app/image-classifier/node_modules
      - node_modules_shared:/app/shared/doner_types/node_modules
      - node_dist_image-classifier:/app/image-classifier/dist
      - node_dist_shared:/app/shared/doner_types/dist
    command: >-
      sh -c "npm install --prefix ../shared/doner_types &&
      npm run build --prefix ../shared/doner_types &&
      npm install &&
      npm run dev"
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
      - azurite
    ports:
      - 7072:7072
    env_file:
      - ./functions/image-classifier/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

  llm-analyzer:
    image: node:22
    container_name: "llm-analyzer"
    working_dir: /app/llm-analyzer
    volumes:
      - ./functions:/app
      - node_modules_llm-analyzer:/app/llm-analyzer/node_modules
      - node_modules_shared:/app/shared/doner_types/node_modules
      - node_dist_llm-analyzer:/app/llm-analyzer/dist
      - node_dist_shared:/app/shared/doner_types/dist
    command: >-
      sh -c "npm install --prefix ../shared/doner_types &&
      npm run build --prefix ../shared/doner_types &&
      npm install &&
      npm run dev"
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
    ports:
      - 7073:7073
    env_file:
      - ./functions/llm-analyzer/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

  places-reader:
    image: node:22
    container_name: "places-reader"
    working_dir: /app
    restart: always
    volumes:
      - ./helper/service-bus-reader:/app
      - node_modules_service-bus-reader:/app/node_modules
      - node_dist_service-bus-reader:/app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - servicebus-emulator
    environment:
      SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      QUEUE_NAME: "places"
      BATCH_SIZE: "10"
  
  image-classifier-reader:
    image: node:22
    container_name: "image-classifier-reader"
    working_dir: /app
    restart: always
    volumes:
      - ./helper/service-bus-reader:/app
      - node_modules_service-bus-reader:/app/node_modules
      - node_dist_service-bus-reader:/app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - servicebus-emulator
    environment:
      SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      QUEUE_NAME: "classified-images"
      BATCH_SIZE: "10"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  
  cosmosdb-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    container_name: "cosmosdb-emulator"
    hostname: cosmosdb-emulator
    restart: always
    command: ["--gateway-endpoint", "cosmosdb-emulator"]
    ports:
      - "8081:8081"
      - "1234:1234"

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: "servicebus-emulator"
    hostname: servicebus-emulator
    restart: always
    volumes:
      - ./localdev/ServiceBus_Emulator.Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "Secure!12346"
      ACCEPT_EULA: "Y"
    depends_on:
      sqledge:
        condition: service_healthy
    
  sqledge:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "sqledge"
    hostname: sqledge
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Secure!12346"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Secure!12346' -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  node_modules_place-search:
  node_modules_image-classifier:
  node_modules_llm-analyzer:
  node_modules_service-bus-reader:
  node_modules_shared:
  node_dist_place-search:
  node_dist_image-classifier:
  node_dist_llm-analyzer:
  node_dist_service-bus-reader:
  node_dist_shared:
