include:
  - ./localdev/emulators.yaml

services:

  doner_types_builder:
    image: node:22
    container_name: doner_types_builder
    restart: no
    working_dir: /app/shared/doner_types
    volumes:
      - ./functions:/app
      - doner_types_node_modules:/app/shared/doner_types/node_modules
      - doner_types_node_dist:/app/shared/doner_types/dist
      - /app/node_modules
    command: >-
      sh -c "
      npm install &&
      npm run build
      "

  place-search:
    image: node:22
    platform: linux/amd64
    container_name: "place-search"
    working_dir: /app/place-search
    volumes:
      - ./functions:/app
      - doner_types_node_dist:/app/shared/doner_types/dist
      - /app/node_modules
      - /app/place-search/node_modules
      - /app/place-search/dist

    command: >-
      sh -c "
      npm install &&
      npm run dev
      "
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
      - azurite
      - doner_types_builder
    ports:
      - 7071:7071
    env_file:
      - ./functions/place-search/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

  image-classifier:
    image: node:22
    platform: linux/amd64
    container_name: "image-classifier"
    working_dir: /app/image-classifier
    volumes:
      - ./functions:/app
      - doner_types_node_dist:/app/shared/doner_types/dist
      - /app/node_modules
      - /app/image-classifier/node_modules
      - /app/image-classifier/dist
    command: >-
      sh -c "
      npm install &&
      npm run dev
      "
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
      - azurite
      - doner_types_builder
    ports:
      - 7072:7072
    env_file:
      - ./functions/image-classifier/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

  llm-analyzer:
    image: node:22
    platform: linux/amd64
    container_name: "llm-analyzer"
    working_dir: /app/llm-analyzer
    volumes:
      - ./functions:/app
      - doner_types_node_dist:/app/shared/doner_types/dist
      - /app/node_modules
      - /app/llm-analyzer/node_modules
      - /app/llm-analyzer/dist
    command: >-
      sh -c "
      npm install &&
      npm run dev
      "
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
      - doner_types_builder
    ports:
      - 7073:7073
    env_file:
      - ./functions/llm-analyzer/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

  shops:
    image: node:22
    platform: linux/amd64
    container_name: shops
    working_dir: /app/shops
    volumes:
      - ./functions:/app
      - doner_types_node_dist:/app/shared/doner_types/dist
      - /app/node_modules
      - /app/shops/node_modules
      - /app/shops/dist
    command: >-
      sh -c "
      npm install &&
      npm run dev
      "
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
      - doner_types_builder
    ports:
      - 7074:7074
    env_file:
      - ./functions/shops/.env
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

volumes:
  doner_types_node_modules:
  doner_types_node_dist:
