services:
  place-search:
    image: node:22
    container_name: "place-search"
    working_dir: /app/place-search
    volumes:
      - ./functions:/app
      - node_modules_place-search:/app/place-search/node_modules
      - node_modules_shared:/app/shared/doner_types/node_modules
    command: >-
      sh -c "npm install --prefix ../shared/doner_types &&
      npm run build --prefix ../shared/doner_types &&
      npm install &&
      npm run dev"
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
    environment:
      PLACE_SEARCH_CRON: "*/10 * * * * *"
      GOOGLE_PLACES_API_KEY: YOUR_GOOGLE_PLACES_API_KEY_HERE
      PLACE_SEARCH_SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      PLACE_SEARCH_SERVICEBUS_QUEUE_NAME: "places"
      PLACE_SEARCH_SERVICEBUS_QUEUE_NAME_GRID_POINTS: "grid-points"
      PLACE_SEARCH_COSMOSDB_CONNECTION_STRING: "AccountEndpoint=http://cosmosdb-emulator:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;"
      PLACE_SEARCH_COSMOSDB_DATABASE_NAME: "DoenerGuideDB"
      PLACE_SEARCH_COSMOSDB_CONTAINER_NAME: "Places"

  image-classifier:
    image: node:22
    container_name: "image-classifier"
    working_dir: /app/image-classifier
    volumes:
      - ./functions:/app
      - node_modules_image-classifier:/app/image-classifier/node_modules
      - node_modules_shared:/app/shared/doner_types/node_modules
    command: >-
      sh -c "npm install --prefix ../shared/doner_types &&
      npm run build --prefix ../shared/doner_types &&
      npm install &&
      npm run dev"
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
    environment:
      IMAGE_CLASSIFIER_SERVICEBUS_CONNECTION_STRING_INPUT: "Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      IMAGE_CLASSIFIER_SERVICEBUS_QUEUE_NAME_INPUT: "places"
      IMAGE_CLASSIFIER_SERVICEBUS_CONNECTION_STRING_OUTPUT: "Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      IMAGE_CLASSIFIER_SERVICEBUS_QUEUE_NAME_OUTPUT: "images-classified"
      IMAGE_CLASSIFIER_COSMOSDB_CONNECTION_STRING: "AccountEndpoint=http://cosmosdb-emulator:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;"
      IMAGE_CLASSIFIER_COSMOSDB_DATABASE_NAME: "DoenerGuideDB"
      IMAGE_CLASSIFIER_COSMOSDB_CONTAINER_NAME: "Places"

  llm-analyzer:
    image: node:22
    container_name: "llm-analyzer"
    working_dir: /app/llm-analyzer
    volumes:
      - ./functions:/app
      - node_modules_llm-analyzer:/app/llm-analyzer/node_modules
      - node_modules_shared:/app/shared/doner_types/node_modules
    command: >-
      sh -c "npm install --prefix ../shared/doner_types &&
      npm run build --prefix ../shared/doner_types &&
      npm install &&
      npm run dev"
    depends_on:
      - servicebus-emulator
      - cosmosdb-emulator
    environment:
      LLM_ANALYZER_SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      LLM_ANALYZER_SERVICEBUS_QUEUE_NAME_INPUT: "images-classified"
      LLM_ANALYZER_COSMOSDB_CONNECTION_STRING: "AccountEndpoint=http://cosmosdb-emulator:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;"
      LLM_ANALYZER_COSMOSDB_DATABASE_NAME: "DoenerGuideDB"
      LLM_ANALYZER_COSMOSDB_CONTAINER_NAME: "Places"

  places-reader:
    image: node:22
    container_name: "places-reader"
    working_dir: /app
    restart: always
    volumes:
      - ./helper/service-bus-reader:/app
      - node_modules_service-bus-reader:/app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - servicebus-emulator
    environment:
      SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      QUEUE_NAME: "places"
      BATCH_SIZE: "10"

  image-classifier-reader:
    image: node:22
    container_name: "image-classifier-reader"
    working_dir: /app
    restart: always
    volumes:
      - ./helper/service-bus-reader:/app
      - node_modules_service-bus-reader:/app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - servicebus-emulator
    environment:
      SERVICEBUS_CONNECTION_STRING: "Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      QUEUE_NAME: "images-classified"
      BATCH_SIZE: "10"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    environment:
      AZURITE_ACCOUNTS: test_account_place_search_timer_trigger:secure_key

  cosmosdb-emulator:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    container_name: "cosmosdb-emulator"
    hostname: cosmosdb-emulator
    restart: always
    command: ["--gateway-endpoint", "cosmosdb-emulator"]
    ports:
      - "8081:8081"
      - "1234:1234"

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: "servicebus-emulator"
    hostname: servicebus-emulator
    restart: always
    volumes:
      - ./localdev/ServiceBus_Emulator.Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "Secure!12346"
      ACCEPT_EULA: "Y"
    depends_on:
      - sqledge

  sqledge:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    container_name: "sqledge"
    hostname: sqledge
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Secure!12346"

volumes:
  node_modules_place-search:
  node_modules_image-classifier:
  node_modules_llm-analyzer:
  node_modules_service-bus-reader:
  node_modules_shared:
