name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yaml"
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Export Azure Static Web Apps API Token and Backend Mock URL
        id: export-token
        working-directory: infrastructure
        run: |
          terraform init
          TOKEN=$(terraform output -raw static_web_app_api_token)
          echo "::add-mask::$TOKEN"
          echo "api_token=$TOKEN" >> $GITHUB_OUTPUT
          MOCK_URL=$(terraform output -raw api_mock_url)
          echo "api_mock_url=$MOCK_URL" >> $GITHUB_OUTPUT

      - name: Build Frontend
        working-directory: frontend
        env:
          NEXT_PUBLIC_API_URL: ${{ steps.export-token.outputs.api_mock_url }}
          NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}
        run: |
          npm --prefix ../api_mock ci && npm ci --ignore-scripts
          npm --prefix ../api_mock run start & npm run build

      - name: Deploy Frontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.export-token.outputs.api_token }}
          action: "upload"
          app_location: "frontend/out"
          skip_api_build: true
          skip_app_build: true